@include('counsellor.reports.pdf._header')
<div class="page-header" style="background:#2563eb;">
    <div class="report-num">Report #31 &mdash; Luwinga Secondary School</div>
    <h1>Assessment Engagement Report</h1>
    <div class="subtitle">Completion rates by form, stream, and demographic factors</div>
</div>
<div class="meta">
    <span>Generated by {{ $generatedBy }} &mdash; {{ $generatedAt }}</span>
</div>

<div class="stat-row">
    <div class="stat-box"><div class="val">{{ number_format($data['total_students']) }}</div><div class="lbl">Total Students</div></div>
    <div class="stat-box"><div class="val" style="color:#1d4ed8;">{{ number_format($data['completed_assessments']) }}</div><div class="lbl">Completed</div></div>
    <div class="stat-box"><div class="val" style="color:#2563eb;">{{ $data['completion_rate'] }}%</div><div class="lbl">Completion Rate</div></div>
</div>

<h2>Completion by Form Level</h2>
<table>
    <thead><tr><th>Form</th><th>Total</th><th>Completed</th><th>Rate</th></tr></thead>
    <tbody>
    @foreach($data['by_form'] as $form => $stats)
    <tr>
        <td>{{ $form }}</td>
        <td>{{ $stats['total'] }}</td>
        <td>{{ $stats['completed'] }}</td>
        <td>{{ $stats['rate'] }}%</td>
    </tr>
    @endforeach
    </tbody>
</table>

<h2>Completion by Stream</h2>
<table>
    <thead><tr><th>Stream</th><th>Total</th><th>Completed</th><th>Rate</th></tr></thead>
    <tbody>
    @foreach($data['by_stream'] as $stream => $stats)
    <tr>
        <td>{{ $stream }}</td>
        <td>{{ $stats['total'] }}</td>
        <td>{{ $stats['completed'] }}</td>
        <td>{{ $stats['rate'] }}%</td>
    </tr>
    @endforeach
    </tbody>
</table>

@if($data['monthly_trends']->count())
<h2>Monthly Trend</h2>
<table>
    <thead><tr><th>Month</th><th>Assessments Completed</th></tr></thead>
    <tbody>
    @foreach($data['monthly_trends'] as $trend)
    <tr><td>{{ $trend->month }}</td><td>{{ $trend->count }}</td></tr>
    @endforeach
    </tbody>
</table>
@endif

<div class="footer">
    <span>Luwinga Secondary School &mdash; Smart Guidance Tool</span>
    <span>{{ $generatedAt }}</span>
</div>
</body></html>
