@include('counsellor.reports.pdf._header')
<div class="page-header" style="background:#000000;">
    <div class="report-num">Report #32 &mdash; Luwinga Secondary School</div>
    <h1>Career Path Tracking</h1>
    <div class="subtitle">Longitudinal tracking of students' career preference changes over time</div>
</div>
<div class="meta">
    <span>Generated by {{ $generatedBy }} &mdash; {{ $generatedAt }}</span>
    <span>{{ count($trackingData) }} students tracked</span>
</div>

<table>
    <thead><tr><th>Student</th><th>Latest Career</th><th>Assessments</th><th>Trend</th><th>Career History</th></tr></thead>
    <tbody>
    @forelse($trackingData as $record)
    <tr>
        <td><strong>{{ $record['student_name'] }}</strong></td>
        <td>{{ $record['latest_career'] }}</td>
        <td>{{ count($record['history']) }}</td>
        <td>{{ $record['trend'] }}</td>
        <td style="font-size:9px;">
            @foreach($record['history'] as $h)
            {{ $h['career'] }} ({{ $h['score'] }}%) {{ $h['date'] }}@if(!$loop->last) &rarr; @endif
            @endforeach
        </td>
    </tr>
    @empty
    <tr><td colspan="5" style="text-align:center;color:#000000;">No longitudinal data available yet.</td></tr>
    @endforelse
    </tbody>
</table>

<div class="footer">
    <span>Luwinga Secondary School &mdash; Smart Guidance Tool</span>
    <span>{{ $generatedAt }}</span>
</div>
</body></html>
