@include('counsellor.reports.pdf._header')
<div class="page-header" style="background:#2563eb;">
    <div class="report-num">Report #27 &mdash; Luwinga Secondary School</div>
    <h1>Career Library Report</h1>
    <div class="subtitle">Complete catalog of careers with subject requirements and university pathways</div>
</div>
<div class="meta">
    <span>Generated by {{ $generatedBy }} &mdash; {{ $generatedAt }}</span>
    <span>{{ $careers->count() }} careers</span>
</div>

@foreach($careers->groupBy('category') as $category => $group)
<h2>{{ $category }} ({{ $group->count() }})</h2>
<table>
    <thead><tr><th>Career</th><th>Required Subjects</th><th>Uni Programs</th><th>Growth</th></tr></thead>
    <tbody>
    @foreach($group as $career)
    <tr>
        <td><strong>{{ $career->title }}</strong></td>
        <td>{{ $career->subjects->pluck('code')->join(', ') ?: 'N/A' }}</td>
        <td>{{ $career->universityPrograms->count() }}</td>
        <td>{{ $career->growth_outlook ?? 'Good' }}</td>
    </tr>
    @endforeach
    </tbody>
</table>
@endforeach

<div class="footer">
    <span>Luwinga Secondary School &mdash; Smart Guidance Tool</span>
    <span>{{ $generatedAt }}</span>
</div>
</body></html>
