@include('counsellor.reports.pdf._header')
<div class="page-header" style="background:#2563eb;">
    <div class="report-num">Report #29 &mdash; Luwinga Secondary School</div>
    <h1>Career Fair Recommendations</h1>
    <div class="subtitle">Suggested career clusters to feature based on student interest data</div>
</div>
<div class="meta">
    <span>Generated by {{ $generatedBy }} &mdash; {{ $generatedAt }}</span>
</div>

@foreach($recommendations as $category => $info)
<h2>{{ $category }} &mdash; {{ number_format($info['count']) }} students interested</h2>
<table>
    <thead><tr><th>Career to Feature</th><th>Avg Match Score</th></tr></thead>
    <tbody>
    @foreach($info['careers'] as $career)
    <tr>
        <td>{{ $career['title'] }}</td>
        <td>{{ $career['avg_score'] }}%</td>
    </tr>
    @endforeach
    </tbody>
</table>
@endforeach

<div class="footer">
    <span>Luwinga Secondary School &mdash; Smart Guidance Tool</span>
    <span>{{ $generatedAt }}</span>
</div>
</body></html>
