@include('counsellor.reports.pdf._header')
<div class="page-header">
    <div class="report-num">Report #24 &mdash; Luwinga Secondary School</div>
    <h1>School-Wide Career Analytics</h1>
    <div class="subtitle">Comprehensive career interest analysis with demographic breakdowns</div>
</div>
<div class="meta">
    <span>Generated by {{ $generatedBy }} &mdash; {{ $generatedAt }}</span>
    <span>Total students: {{ $data['total_students'] }}</span>
</div>

<div class="stat-row">
    <div class="stat-box"><div class="val">{{ $data['total_students'] }}</div><div class="lbl">Total Students</div></div>
    <div class="stat-box"><div class="val">{{ $data['completed_assessments'] }}</div><div class="lbl">Assessments Completed</div></div>
    <div class="stat-box"><div class="val">{{ $data['completion_rate'] }}%</div><div class="lbl">Completion Rate</div></div>
    <div class="stat-box"><div class="val">{{ count($data['career_interests']) }}</div><div class="lbl">Career Categories</div></div>
</div>

<h2>Career Interest Distribution</h2>
@foreach($data['career_interests'] as $category => $count)
@php $pct = $data['total_students'] > 0 ? round(($count / $data['total_students']) * 100) : 0; @endphp
<div style="margin-bottom:8px;">
    <div style="display:flex;justify-content:space-between;font-size:10px;margin-bottom:2px;">
        <span>{{ $category }}</span><span>{{ $count }} students ({{ $pct }}%)</span>
    </div>
    <div class="bar-wrap"><div class="bar-fill" style="width:{{ $pct }}%"></div></div>
</div>
@endforeach

<h2>Top Career Matches</h2>
<table>
    <thead><tr><th>#</th><th>Career</th><th>Category</th><th>Matches</th><th>Avg Score</th></tr></thead>
    <tbody>
    @foreach($data['top_careers'] as $i => $career)
    <tr>
        <td>{{ $i + 1 }}</td>
        <td>{{ $career->recommended->title ?? 'N/A' }}</td>
        <td>{{ $career->recommended->category ?? 'N/A' }}</td>
        <td>{{ number_format($career->count) }}</td>
        <td>{{ round($career->avg_score, 1) }}%</td>
    </tr>
    @endforeach
    </tbody>
</table>

<h2>Breakdown by Form</h2>
<table>
    <thead><tr><th>Form</th><th>Count</th></tr></thead>
    <tbody>
    @foreach($data['form_breakdown'] as $form => $count)
    <tr><td>{{ $form }}</td><td>{{ $count }}</td></tr>
    @endforeach
    </tbody>
</table>

<div class="footer">
    <span>Luwinga Secondary School &mdash; Smart Guidance Tool</span>
    <span>{{ $generatedAt }}</span>
</div>
</body></html>
