@include('counsellor.reports.pdf._header')
<div class="page-header" style="background:#2563eb;">
    <div class="report-num">Report #25 &mdash; Luwinga Secondary School</div>
    <h1>Student Intervention Priority List</h1>
    <div class="subtitle">Ranked list of students needing immediate career guidance</div>
</div>
<div class="meta">
    <span>Generated by {{ $generatedBy }} &mdash; {{ $generatedAt }}</span>
    <span>{{ count($students) }} students flagged</span>
</div>

@php
    $high   = collect($students)->where('priority','High')->count();
    $medium = collect($students)->where('priority','Medium')->count();
@endphp
<div class="stat-row">
    <div class="stat-box"><div class="val" style="color:#2563eb;">{{ $high }}</div><div class="lbl">High Priority</div></div>
    <div class="stat-box"><div class="val" style="color:#000000;">{{ $medium }}</div><div class="lbl">Medium Priority</div></div>
    <div class="stat-box"><div class="val">{{ count($students) }}</div><div class="lbl">Total Flagged</div></div>
</div>

<table>
    <thead><tr><th>#</th><th>Student</th><th>Form</th><th>Stream</th><th>Assessment</th><th>Best Match</th><th>Priority</th><th>Recommended Action</th></tr></thead>
    <tbody>
    @foreach($students as $i => $student)
    <tr>
        <td>{{ $i + 1 }}</td>
        <td>{{ $student['name'] }}</td>
        <td>{{ $student['form'] }}</td>
        <td>{{ $student['stream'] }}</td>
        <td><span class="badge {{ $student['has_assessment'] ? 'badge-green' : 'badge-red' }}">{{ $student['has_assessment'] ? 'Done' : 'Pending' }}</span></td>
        <td>{{ $student['best_match_score'] }}%</td>
        <td><span class="badge {{ $student['priority'] === 'High' ? 'badge-red' : 'badge-orange' }}">{{ $student['priority'] }}</span></td>
        <td>{{ $student['recommended_action'] }}</td>
    </tr>
    @endforeach
    </tbody>
</table>

<div class="footer">
    <span>Luwinga Secondary School &mdash; Smart Guidance Tool</span>
    <span>{{ $generatedAt }}</span>
</div>
</body></html>
