@include('counsellor.reports.pdf._header')
<div class="page-header" style="background:#2563eb;">
    <div class="report-num">Report #26 &mdash; Luwinga Secondary School</div>
    <h1>Counselling Session Log</h1>
    <div class="subtitle">Complete history of counselling sessions with notes</div>
</div>
<div class="meta">
    <span>Generated by {{ $generatedBy }} &mdash; {{ $generatedAt }}</span>
    <span>{{ $sessions->count() }} sessions</span>
</div>

<table>
    <thead><tr><th>Date</th><th>Student</th><th>Notes</th></tr></thead>
    <tbody>
    @forelse($sessions as $session)
    <tr>
        <td style="text-white-space:nowrap;">{{ $session->created_at->format('d M Y H:i') }}</td>
        <td>{{ $session->user->name ?? 'Unknown' }}</td>
        <td>{{ $session->meta['notes'] ?? $session->description ?? 'No notes recorded' }}</td>
    </tr>
    @empty
    <tr><td colspan="3" style="text-align:center;color:#000000;">No sessions recorded yet.</td></tr>
    @endforelse
    </tbody>
</table>

<div class="footer">
    <span>Luwinga Secondary School &mdash; Smart Guidance Tool</span>
    <span>{{ $generatedAt }}</span>
</div>
</body></html>
