@include('counsellor.reports.pdf._header')
<div class="page-header" style="background:#000000;">
    <div class="report-num">Report #30 &mdash; Luwinga Secondary School</div>
    <h1>Student Success Stories</h1>
    <div class="subtitle">Students with high career match scores who followed recommendations</div>
</div>
<div class="meta">
    <span>Generated by {{ $generatedBy }} &mdash; {{ $generatedAt }}</span>
    <span>{{ count($stories) }} students</span>
</div>

<table>
    <thead><tr><th>Student</th><th>Form</th><th>Stream</th><th>Top Career</th><th>Match Score</th><th>Saved Recs</th></tr></thead>
    <tbody>
    @forelse($stories as $story)
    <tr>
        <td><strong>{{ $story['name'] }}</strong></td>
        <td>{{ $story['form'] }}</td>
        <td>{{ $story['stream'] }}</td>
        <td>{{ $story['top_career'] }}</td>
        <td><span class="badge badge-green">{{ $story['match_score'] }}%</span></td>
        <td>{{ $story['saved_recommendations'] }}</td>
    </tr>
    @empty
    <tr><td colspan="6" style="text-align:center;color:#000000;">No success stories yet.</td></tr>
    @endforelse
    </tbody>
</table>

<div class="footer">
    <span>Luwinga Secondary School &mdash; Smart Guidance Tool</span>
    <span>{{ $generatedAt }}</span>
</div>
</body></html>
