@include('counsellor.reports.pdf._header')
<div class="page-header" style="background:#2563eb;">
    <div class="report-num">Report #28 &mdash; Luwinga Secondary School</div>
    <h1>University Program Mapping</h1>
    <div class="subtitle">All university programs with entry requirements and feeder careers</div>
</div>
<div class="meta">
    <span>Generated by {{ $generatedBy }} &mdash; {{ $generatedAt }}</span>
    <span>{{ $programs->count() }} programs</span>
</div>

<table>
    <thead><tr><th>Program</th><th>University</th><th>Min Points</th><th>Required Subjects</th><th>Feeder Careers</th></tr></thead>
    <tbody>
    @forelse($programs as $program)
    <tr>
        <td><strong>{{ $program->name }}</strong>@if($program->duration)<br><span style="color:#000000;font-size:9px;">{{ $program->duration }}</span>@endif</td>
        <td>{{ $program->university_name ?? 'N/A' }}</td>
        <td><strong>{{ $program->min_points ?? 'N/A' }}</strong></td>
        <td>{{ $program->subjects->pluck('code')->join(', ') ?: 'N/A' }}</td>
        <td>{{ $program->careers->pluck('title')->join(', ') ?: 'N/A' }}</td>
    </tr>
    @empty
    <tr><td colspan="5" style="text-align:center;color:#000000;">No programs found.</td></tr>
    @endforelse
    </tbody>
</table>

<div class="footer">
    <span>Luwinga Secondary School &mdash; Smart Guidance Tool</span>
    <span>{{ $generatedAt }}</span>
</div>
</body></html>
