<?php

namespace Database\Seeders;

use App\Models\{Subject, UniversityProgram};
use Illuminate\Database\Seeder;

class UniversityProgramSeeder extends Seeder
{
    /**
     * 'required_subjects'  → subject codes that MUST be passed.
     * 'preferred_subjects' → codes that give an advantage or are among "any X from" lists.
     * 'grades'             → ['SUBCODE' => N] overrides the default minimum MSCE grade (6=Credit)
     *                        for specific subjects. Lower N = higher standard required.
     *                        1–2 = Distinction · 3–4 = Strong Credit · 5–6 = Credit · 7–8 = Pass
     */
    public function run(): void
    {
        $programs = $this->programs();

        foreach ($programs as $data) {
            $program = UniversityProgram::updateOrCreate(
                ['name' => $data['name'], 'university' => $data['university']],
                [
                    'faculty'            => $data['faculty'],
                    'minimum_points'     => $data['minimum_points'],
                    'entry_requirements' => $data['entry_requirements'],
                    'description'        => $data['description'] ?? null,
                ]
            );

            $grades = $data['grades'] ?? [];

            // Re-sync subjects to avoid stale pivot rows on re-seed
            $program->subjects()->detach();
            $this->attachSubjects($program, $data['required_subjects'], 'required', $grades);
            if (!empty($data['preferred_subjects'])) {
                $this->attachSubjects($program, $data['preferred_subjects'], 'preferred', $grades);
            }
        }

        $this->command->info('✅ University programs seeded/updated: ' . count($programs));
    }

    /**
     * @param array $codes    Simple list of subject codes
     * @param array $grades   ['CODE' => minGrade] — overrides the default 6 (Credit) per subject
     */
    private function attachSubjects(
        UniversityProgram $program,
        array $codes,
        string $requirement,
        array $grades = []
    ): void {
        foreach ($codes as $code) {
            $subject = Subject::where('code', $code)->first();
            if (!$subject) {
                $this->command->warn("  ⚠ Subject code '{$code}' not found — skipped.");
                continue;
            }
            $program->subjects()->attach($subject->id, [
                'requirement'   => $requirement,
                'minimum_grade' => $grades[$code] ?? 6,
            ]);
        }
    }

    private function programs(): array
    {
        return [

            // ═══════════════════════════════════════════════════════════════
            // A. KAMUZU UNIVERSITY OF HEALTH SCIENCES (KUHeS)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'               => 'Bachelor of Medicine / Bachelor of Surgery (MBBCh)',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Medicine and Oral Health',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, plus min 3 points each in Mathematics, Biology, Physics and Chemistry or General Science.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'PHY01', 'CHEM01'],
                'preferred_subjects' => ['GSCI01'],
                'grades'             => ['MATH01' => 3, 'BIO01' => 3, 'PHY01' => 3, 'CHEM01' => 3],
            ],
            [
                'name'               => 'Bachelor of Dental Surgery',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Medicine and Oral Health',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, plus min 3 points each in Mathematics, Biology, Physics and Chemistry or General Science.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'PHY01', 'CHEM01'],
                'preferred_subjects' => ['GSCI01'],
                'grades'             => ['MATH01' => 3, 'BIO01' => 3, 'PHY01' => 3, 'CHEM01' => 3],
            ],
            [
                'name'               => 'Bachelor of Medical Laboratory Sciences (Honours)',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Life Sciences & Allied Health Professions',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics, plus min 4 points in Biology, Chemistry or General Science and a third science subject.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01'],
                'preferred_subjects' => ['PHY01', 'GSCI01'],
                'grades'             => ['BIO01' => 4, 'CHEM01' => 4],
            ],
            [
                'name'               => 'Bachelor of Pharmacy (Honours)',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Life Sciences & Allied Health Professions',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, plus min 4 points in Mathematics, Biology, Chemistry or General Science and a fourth science subject.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01'],
                'preferred_subjects' => ['PHY01', 'GSCI01'],
                'grades'             => ['MATH01' => 4, 'BIO01' => 4, 'CHEM01' => 4],
            ],
            [
                'name'               => 'Bachelor of Physiotherapy (Honours)',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Life Sciences & Allied Health Professions',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics, plus min 4 points in Biology, Chemistry or General Science and a third science subject.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01'],
                'preferred_subjects' => ['PHY01', 'GSCI01'],
                'grades'             => ['BIO01' => 4, 'CHEM01' => 4],
            ],
            [
                'name'               => 'Bachelor of Biomedical Sciences (Honours)',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Life Sciences & Allied Health Professions',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, plus min 4 points in Mathematics, Biology, Physics and Chemistry or General Science.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'PHY01', 'CHEM01'],
                'preferred_subjects' => ['GSCI01'],
                'grades'             => ['MATH01' => 4, 'BIO01' => 4, 'PHY01' => 4, 'CHEM01' => 4],
            ],
            [
                'name'               => 'Bachelor of Occupational Therapy (Honours)',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Life Sciences & Allied Health Professions',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics, plus min 4 points in Biology, Chemistry or General Science and a third science subject.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01'],
                'preferred_subjects' => ['PHY01', 'GSCI01'],
                'grades'             => ['BIO01' => 4, 'CHEM01' => 4],
            ],
            [
                'name'               => 'Bachelor of Science in Nutrition and Dietetics (Honours)',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Global & Public Health',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics, plus min 4 points in Biology, Chemistry or General Science and a third science subject.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01'],
                'preferred_subjects' => ['PHY01', 'GSCI01'],
                'grades'             => ['BIO01' => 4, 'CHEM01' => 4],
            ],
            [
                'name'               => 'Bachelor of Public Health (Honours)',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Global & Public Health',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics; credit in Biology, Chemistry or General Science.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01'],
                'preferred_subjects' => ['CHEM01', 'GSCI01', 'PHY01'],
            ],
            [
                'name'               => 'Bachelor of Environmental Health Sciences (Honours)',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Global & Public Health',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology and Chemistry or General Science.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01'],
                'preferred_subjects' => ['PHY01', 'GSCI01', 'GEOG01'],
            ],
            [
                'name'               => 'Bachelor of Science in Radiography and Medical Imaging (Honours)',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Life Sciences & Allied Health Professions',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Physics, Biology and Chemistry or General Science.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01', 'BIO01', 'CHEM01'],
                'preferred_subjects' => ['GSCI01'],
            ],
            [
                'name'               => 'Bachelor of Health Information Management (Honours)',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Global & Public Health',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics; credit in Biology or General Science.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BIO01', 'COMP01', 'GSCI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Adult Health Nursing',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Nursing',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Physics, Biology, Chemistry or General Science. Must specify Nursing as first choice.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['GSCI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Child Health Nursing',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Nursing',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Physics, Biology, Chemistry or General Science. Must specify Nursing as first choice.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['GSCI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Nursing and Midwifery',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Nursing',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Physics, Biology, Chemistry or General Science. Must specify Nursing as first choice.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['GSCI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Community Health Nursing',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Nursing',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Physics, Biology, Chemistry or General Science. Must specify Nursing as first choice.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['GSCI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Mental Health and Psychiatric Nursing',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Nursing',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Physics, Biology, Chemistry or General Science. Must specify Nursing as first choice.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['GSCI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Midwifery',
                'university'         => 'Kamuzu University of Health Sciences (KUHeS)',
                'faculty'            => 'School of Maternal, Neonatal & Reproductive Health',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Physics, Biology, Chemistry or General Science. Must specify Midwifery as first choice.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['GSCI01'],
            ],

            // ═══════════════════════════════════════════════════════════════
            // B. LILONGWE UNIVERSITY OF AGRICULTURE AND NATURAL RESOURCES (LUANAR)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'               => 'Bachelor of Science in Agricultural Engineering (Honours)',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Agriculture',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Irrigation Engineering (Honours)',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Agriculture',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Environmental Engineering (Honours)',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Agriculture',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Animal Science',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Agriculture',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Agriculture',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Agriculture',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['AGRI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Crop Sciences',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Agriculture',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['AGRI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Biotechnology',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Agriculture',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Horticulture',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Agriculture',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology and Chemistry.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01'],
                'preferred_subjects' => ['PHY01', 'AGRI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Soil and Water Conservation',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Agriculture',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['GEOG01', 'AGRI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Agribusiness Management',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Development Studies',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['BUS01'],
            ],
            [
                'name'               => 'Bachelor of Science in Agricultural Economics',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Development Studies',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['BIO01', 'BUS01'],
            ],
            [
                'name'               => 'Bachelor of Science in Rural Development',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Development Studies',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics and at least two of Biology, Chemistry, Geography or Social Studies.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BIO01', 'CHEM01', 'GEOG01', 'SOC01'],
            ],
            [
                'name'               => 'Bachelor of Science in Communication and Journalism',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Development Studies',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Food Science and Technology',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Food and Human Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Nutrition and Food Science',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Food and Human Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Home Economics and Family Sciences',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Food and Human Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics and Biology.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01'],
                'preferred_subjects' => ['CHEM01', 'HOME01'],
            ],
            [
                'name'               => 'Bachelor of Science in Aquaculture and Fisheries Science',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Natural Resources',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Environmental Sciences',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Natural Resources',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['GEOG01'],
            ],
            [
                'name'               => 'Bachelor of Science in Forestry',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Natural Resources',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Wildlife and Range Management',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Natural Resources',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['GEOG01'],
            ],
            [
                'name'               => 'Bachelor of Veterinary Medicine',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Veterinary Medicine (NRC)',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Applied Computer Science',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Life Sciences and Natural Resources (NRC)',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01'],
                'preferred_subjects' => ['COMP01'],
            ],
            [
                'name'               => 'Bachelor of Science in Mathematics and Statistics',
                'university'         => 'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
                'faculty'            => 'Faculty of Life Sciences and Natural Resources (NRC)',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Physics and Chemistry.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01', 'CHEM01'],
                'preferred_subjects' => ['BIO01'],
            ],

            // ═══════════════════════════════════════════════════════════════
            // C. MALAWI UNIVERSITY OF BUSINESS AND APPLIED SCIENCES (MUBAS)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'               => 'Bachelor of Architecture (Honours)',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Built Environment',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Chemistry and Physics or General Science. Credits in Technical Drawing, Art, Design Technology and Geography are an added advantage.',
                'required_subjects'  => ['ENG01', 'MATH01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['TECH01', 'ART01', 'GEOG01', 'GSCI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Real Estate (Honours)',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Built Environment',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics and Geography.',
                'required_subjects'  => ['ENG01', 'MATH01', 'GEOG01'],
                'preferred_subjects' => ['BUS01'],
            ],
            [
                'name'               => 'Bachelor of Science in Land Surveying (Honours)',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Built Environment',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Geography, Chemistry and Physics or General Science.',
                'required_subjects'  => ['ENG01', 'MATH01', 'GEOG01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['GSCI01', 'TECH01'],
            ],
            [
                'name'               => 'Bachelor of Urban and Regional Planning (Honours)',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Built Environment',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics and Geography.',
                'required_subjects'  => ['ENG01', 'MATH01', 'GEOG01'],
                'preferred_subjects' => ['BUS01', 'HIST01', 'SOC01'],
            ],
            [
                'name'               => 'Bachelor of Science in Construction Management (Honours)',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Built Environment',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Chemistry and Physics or General Science.',
                'required_subjects'  => ['ENG01', 'MATH01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['GSCI01', 'TECH01'],
            ],
            [
                'name'               => 'Bachelor of Accountancy',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Business and Economic Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['ACC01', 'BUS01'],
            ],
            [
                'name'               => 'Bachelor of Business Administration',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Business and Economic Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BUS01', 'ACC01'],
            ],
            [
                'name'               => 'Bachelor of Commerce in Banking and Finance',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Business and Economic Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['ACC01', 'BUS01'],
            ],
            [
                'name'               => 'Bachelor of Commerce in Economics',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Business and Economic Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BUS01', 'ACC01'],
            ],
            [
                'name'               => 'Bachelor of Commerce in Human Resource Management',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Business and Economic Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BUS01', 'SOC01'],
            ],
            [
                'name'               => 'Bachelor of Commerce in Marketing',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Business and Economic Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BUS01', 'ACC01'],
            ],
            [
                'name'               => 'Bachelor of Commerce in Procurement and Supply Chain Management',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Business and Economic Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BUS01', 'ACC01'],
            ],
            [
                'name'               => 'Bachelor of Science in Information Technology',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Science and Technology',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics and Physics or General Science.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01'],
                'preferred_subjects' => ['COMP01', 'GSCI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Management Information Systems',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Science and Technology',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['COMP01', 'PHY01'],
            ],
            [
                'name'               => 'Bachelor of Science in Software Engineering',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Science and Technology',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English. Minimum grade of 4 points in Physics, Mathematics or General Science.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['PHY01', 'COMP01', 'GSCI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Cybersecurity',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Science and Technology',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics and Physics or General Science.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01'],
                'preferred_subjects' => ['COMP01', 'GSCI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Applied Chemistry',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Science and Technology',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Chemistry and Physics or General Science.',
                'required_subjects'  => ['ENG01', 'MATH01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['BIO01', 'GSCI01'],
            ],
            [
                'name'               => 'Bachelor of Civil Engineering (Honours)',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Engineering',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Chemistry and Physics (General Science).',
                'required_subjects'  => ['ENG01', 'MATH01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['GSCI01'],
            ],
            [
                'name'               => 'Bachelor of Electrical and Electronics Engineering (Honours)',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Engineering',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Chemistry and Physics (General Science).',
                'required_subjects'  => ['ENG01', 'MATH01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['GSCI01'],
            ],
            [
                'name'               => 'Bachelor of Mechanical Engineering (Honours)',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Engineering',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Chemistry and Physics (General Science).',
                'required_subjects'  => ['ENG01', 'MATH01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['GSCI01'],
            ],
            [
                'name'               => 'Bachelor of Engineering in Instrumentation and Automation (Honours)',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Engineering',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['COMP01', 'GSCI01'],
            ],
            [
                'name'               => 'Bachelor of Arts in Journalism',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Education, Communication and Media Studies',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and at least a pass in Mathematics.',
                'required_subjects'  => ['ENG01'],
                'preferred_subjects' => ['MATH01', 'HIST01', 'SOC01'],
            ],
            [
                'name'               => 'Bachelor of Arts in Media Studies',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Education, Communication and Media Studies',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and at least a pass in Mathematics.',
                'required_subjects'  => ['ENG01'],
                'preferred_subjects' => ['MATH01', 'HIST01', 'ART01'],
            ],
            [
                'name'               => 'Bachelor of Education in Early Childhood Development',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Education, Communication and Media Studies',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BIO01', 'SOC01', 'HOME01'],
            ],
            [
                'name'               => 'Bachelor of Education in Educational Leadership and Management',
                'university'         => 'Malawi University of Business and Applied Sciences (MUBAS)',
                'faculty'            => 'School of Education, Communication and Media Studies',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BUS01', 'HIST01'],
            ],

            // ═══════════════════════════════════════════════════════════════
            // D. MALAWI UNIVERSITY OF SCIENCE AND TECHNOLOGY (MUST)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'               => 'Bachelor of Engineering in Biomedical Engineering (Honours)',
                'university'         => 'Malawi University of Science and Technology (MUST)',
                'faculty'            => 'Malawi Institute of Technology',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, plus grade ≤4 in Physics, Chemistry, Biology and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01', 'CHEM01', 'BIO01'],
                'preferred_subjects' => [],
                'grades'             => ['MATH01' => 4, 'PHY01' => 4, 'CHEM01' => 4, 'BIO01' => 4],
            ],
            [
                'name'               => 'Bachelor of Engineering in Chemical Engineering (Honours)',
                'university'         => 'Malawi University of Science and Technology (MUST)',
                'faculty'            => 'Malawi Institute of Technology',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, plus grade ≤4 in Physics, Chemistry, Biology and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01', 'CHEM01', 'BIO01'],
                'preferred_subjects' => [],
                'grades'             => ['MATH01' => 4, 'PHY01' => 4, 'CHEM01' => 4, 'BIO01' => 4],
            ],
            [
                'name'               => 'Bachelor of Engineering in Electronic and Telecommunications Engineering (Honours)',
                'university'         => 'Malawi University of Science and Technology (MUST)',
                'faculty'            => 'Malawi Institute of Technology',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, plus grade ≤4 in Physics, Mathematics and any other science.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01'],
                'preferred_subjects' => ['CHEM01', 'COMP01'],
                'grades'             => ['MATH01' => 4, 'PHY01' => 4],
            ],
            [
                'name'               => 'Bachelor of Engineering in Industrial and Systems Engineering (Honours)',
                'university'         => 'Malawi University of Science and Technology (MUST)',
                'faculty'            => 'Malawi Institute of Technology',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Physics and Chemistry. Grade ≤4 in Physics and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01', 'CHEM01'],
                'preferred_subjects' => ['BIO01'],
                'grades'             => ['MATH01' => 4, 'PHY01' => 4],
            ],
            [
                'name'               => 'Bachelor of Science in Computer Systems and Security',
                'university'         => 'Malawi University of Science and Technology (MUST)',
                'faculty'            => 'Malawi Institute of Technology',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, plus grade ≤4 in Physics and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01'],
                'preferred_subjects' => ['COMP01', 'CHEM01'],
                'grades'             => ['MATH01' => 4, 'PHY01' => 4],
            ],
            [
                'name'               => 'Bachelor of Science in Business Information Technology',
                'university'         => 'Malawi University of Science and Technology (MUST)',
                'faculty'            => 'Malawi Institute of Technology',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, plus grade ≤4 in Physics and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01'],
                'preferred_subjects' => ['COMP01'],
                'grades'             => ['MATH01' => 4, 'PHY01' => 4],
            ],
            [
                'name'               => 'Bachelor of Science in Mathematical Sciences',
                'university'         => 'Malawi University of Science and Technology (MUST)',
                'faculty'            => 'Malawi Institute of Technology',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, plus grade ≤4 in Physics, Chemistry, Biology and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01', 'CHEM01'],
                'preferred_subjects' => ['BIO01'],
                'grades'             => ['MATH01' => 4, 'PHY01' => 4, 'CHEM01' => 4],
            ],
            [
                'name'               => 'Bachelor of Science in Applied Statistics',
                'university'         => 'Malawi University of Science and Technology (MUST)',
                'faculty'            => 'Malawi Institute of Technology',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics and any two sciences.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['PHY01', 'CHEM01', 'BIO01', 'COMP01'],
                'grades'             => ['MATH01' => 4],
            ],
            [
                'name'               => 'Bachelor of Science in Earth Sciences (Geology)',
                'university'         => 'Malawi University of Science and Technology (MUST)',
                'faculty'            => 'Ndata School of Climate and Earth Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Chemistry and Geography, and any three sciences. Grade ≤4 in Physics and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'CHEM01', 'PHY01', 'GEOG01'],
                'preferred_subjects' => ['BIO01'],
                'grades'             => ['MATH01' => 4, 'PHY01' => 4],
            ],
            [
                'name'               => 'Bachelor of Science in Meteorology and Climate Science',
                'university'         => 'Malawi University of Science and Technology (MUST)',
                'faculty'            => 'Ndata School of Climate and Earth Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics and Geography. Grade ≤4 in Physics and Chemistry.',
                'required_subjects'  => ['ENG01', 'MATH01', 'GEOG01', 'PHY01', 'CHEM01'],
                'preferred_subjects' => ['BIO01'],
                'grades'             => ['PHY01' => 4, 'CHEM01' => 4],
            ],
            [
                'name'               => 'Bachelor of Engineering in Sustainable Energy Engineering (Honours)',
                'university'         => 'Malawi University of Science and Technology (MUST)',
                'faculty'            => 'Ndata School of Climate and Earth Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Chemistry. Grade ≤4 in Physics and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01', 'CHEM01'],
                'preferred_subjects' => ['BIO01'],
                'grades'             => ['MATH01' => 4, 'PHY01' => 4],
            ],
            [
                'name'               => 'Bachelor of Science in Environmental Science',
                'university'         => 'Malawi University of Science and Technology (MUST)',
                'faculty'            => 'Ndata School of Climate and Earth Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology and Chemistry.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01'],
                'preferred_subjects' => ['PHY01', 'GEOG01'],
            ],
            [
                'name'               => 'Bachelor of Science in Health Informatics',
                'university'         => 'Malawi University of Science and Technology (MUST)',
                'faculty'            => 'Malawi Institute of Technology',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics and at least one science subject.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BIO01', 'COMP01', 'PHY01'],
            ],

            // ═══════════════════════════════════════════════════════════════
            // E. MZUZU UNIVERSITY (MZUNI)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'               => 'Bachelor of Science in Information and Communication Technology',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Science, Technology and Innovation',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE aggregate ≤30 points; at least 6 credits including English, Mathematics, and any two of: Computer Studies, Biology, Physics, Chemistry, Agriculture.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['COMP01', 'BIO01', 'PHY01', 'CHEM01', 'AGRI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Data Science',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Science, Technology and Innovation',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE aggregate ≤30 points; at least 6 credits including English, Mathematics, and any two of: Computer Studies, Physics, Chemistry, Biology, Agriculture.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['COMP01', 'PHY01', 'CHEM01', 'BIO01', 'AGRI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Renewable Energy Systems Engineering',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Science, Technology and Innovation',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE aggregate ≤30 points; at least 6 credits including English, Mathematics, Physics and Chemistry.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01', 'CHEM01'],
                'preferred_subjects' => ['BIO01'],
            ],
            [
                'name'               => 'Bachelor of Science in Physics and Electronics',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Science, Technology and Innovation',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE aggregate ≤30 points; at least 6 credits including Physics, Chemistry, Mathematics and English.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01', 'CHEM01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Chemistry',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Science, Technology and Innovation',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE aggregate ≤30 points; at least 6 credits including English, Chemistry, Physics, Mathematics and Biology.',
                'required_subjects'  => ['ENG01', 'MATH01', 'CHEM01', 'PHY01', 'BIO01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Mathematics and Statistics (Honours)',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Science, Technology and Innovation',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE aggregate ≤30 points; at least 6 credits including English, Mathematics, Biology, Physics and Chemistry.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'PHY01', 'CHEM01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Biological Sciences',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Science, Technology and Innovation',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE aggregate ≤30 points; at least 6 credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Education (Science)',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Education',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Biology, Mathematics, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Education (ICT)',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Education',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, and any two of: Computer Studies, Physics, Chemistry, Biology, Geography, Technical Drawing.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['COMP01', 'PHY01', 'CHEM01', 'BIO01', 'GEOG01', 'TECH01'],
            ],
            [
                'name'               => 'Bachelor of Education (Languages)',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Education',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and any two of: Chichewa, French, History, Social Studies, Bible Knowledge.',
                'required_subjects'  => ['ENG01'],
                'preferred_subjects' => ['CHI01', 'FRE01', 'HIST01', 'SOC01', 'BK01'],
            ],
            [
                'name'               => 'Bachelor of Education (Social Sciences)',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Education',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics and any two of: History, Geography, Social Studies, Bible Knowledge, Business Studies.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['HIST01', 'GEOG01', 'SOC01', 'BK01', 'BUS01'],
            ],
            [
                'name'               => 'Bachelor of Science in Nursing and Midwifery',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Health Sciences',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE aggregate ≤30 points; at least 6 credits including English, Mathematics, Chemistry, Physics and Biology. Must specify Nursing as first choice.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science (Honours) in Optometry',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Health Sciences',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE aggregate ≤30 points; at least 6 credits including English, Mathematics, Chemistry, Physics and Biology.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Environmental Health Sciences',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Health Sciences',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE aggregate ≤30 points; at least 6 credits including English, Mathematics, Biology and Chemistry.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01'],
                'preferred_subjects' => ['PHY01', 'GEOG01'],
            ],
            [
                'name'               => 'Bachelor of Arts (Politics and Governance)',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Humanities and Social Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, and any two of: Geography, History, Bible Knowledge, Social Studies, Business Studies.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['GEOG01', 'HIST01', 'BK01', 'SOC01', 'BUS01'],
            ],
            [
                'name'               => 'Bachelor of Arts (Development Studies)',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Humanities and Social Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, and any two of: Business Studies, Geography, History, Social Studies, Computer Studies.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BUS01', 'GEOG01', 'HIST01', 'SOC01', 'COMP01'],
            ],
            [
                'name'               => 'Bachelor of Arts in Theology and Religious Studies',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Humanities and Social Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and any two of: Bible Knowledge, History, Social Studies, Chichewa.',
                'required_subjects'  => ['ENG01'],
                'preferred_subjects' => ['BK01', 'HIST01', 'SOC01', 'CHI01'],
            ],
            [
                'name'               => 'Bachelor of Library and Information Science',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Humanities and Social Sciences',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE aggregate ≤30 points; at least 6 credits including English, and any two of: History, Geography, Chichewa, French, Social Studies, Computer Studies, Bible Knowledge.',
                'required_subjects'  => ['ENG01'],
                'preferred_subjects' => ['HIST01', 'GEOG01', 'CHI01', 'FRE01', 'SOC01', 'COMP01', 'BK01'],
            ],
            [
                'name'               => 'Bachelor of Business (Tourism Management)',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Tourism, Hospitality and Management',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE aggregate ≤30 points; at least a credit in English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BUS01', 'HIST01', 'GEOG01'],
            ],
            [
                'name'               => 'Bachelor of Hospitality Management',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Tourism, Hospitality and Management',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE aggregate ≤30 points; at least a credit in English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BUS01', 'HOME01'],
            ],
            [
                'name'               => 'Bachelor of Business Administration in Entrepreneurship',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Tourism, Hospitality and Management',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE aggregate ≤30 points; credits in English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BUS01', 'ACC01'],
            ],
            [
                'name'               => 'Bachelor of Science in Value Chain Agriculture',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Environmental Sciences',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE ≤30 points from 6 best subjects; credits in English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['AGRI01'],
            ],
            [
                'name'               => 'Bachelor of Science in Land Surveying',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Environmental Sciences',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE credits in Mathematics, Geography, English, Physics and any other two subjects; aggregate ≤30.',
                'required_subjects'  => ['ENG01', 'MATH01', 'GEOG01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Environmental Sciences',
                'university'         => 'Mzuzu University',
                'faculty'            => 'Faculty of Environmental Sciences',
                'minimum_points'     => 30,
                'entry_requirements' => 'MSCE aggregate ≤30 points; credits in English, Mathematics, Biology, Chemistry and Geography.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'GEOG01'],
                'preferred_subjects' => ['PHY01'],
            ],

            // ═══════════════════════════════════════════════════════════════
            // F. UNIVERSITY OF MALAWI (UNIMA)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'               => 'Bachelor of Science in Computer Science',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Natural and Applied Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits; at least a distinction in Mathematics and 5 credits including English.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['PHY01', 'COMP01', 'CHEM01'],
                'grades'             => ['MATH01' => 2],
            ],
            [
                'name'               => 'Bachelor of Science in Computer Network Engineering',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Natural and Applied Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits; distinction in Mathematics, strong credit in Physics, and 4 other credits including English.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01'],
                'preferred_subjects' => ['COMP01', 'CHEM01'],
                'grades'             => ['MATH01' => 2, 'PHY01' => 4],
            ],
            [
                'name'               => 'Bachelor of Science in Information Systems',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Natural and Applied Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits; distinction in Mathematics and 5 credits including English.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['COMP01', 'PHY01'],
                'grades'             => ['MATH01' => 2],
            ],
            [
                'name'               => 'Bachelor of Science in Mathematics',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Natural and Applied Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'MSCE with strong credit in Mathematics/Additional Mathematics and at least credits in English, Physics, Chemistry and Biology.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01', 'CHEM01', 'BIO01'],
                'preferred_subjects' => [],
                'grades'             => ['MATH01' => 3],
            ],
            [
                'name'               => 'Bachelor of Science in Physics',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Natural and Applied Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01'],
                'preferred_subjects' => ['CHEM01', 'BIO01'],
                'grades'             => ['PHY01' => 4],
            ],
            [
                'name'               => 'Bachelor of Science in Biological Sciences',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Natural and Applied Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Physics and Chemistry.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'PHY01', 'CHEM01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Science in Chemistry (Honours)',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Natural and Applied Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Physics and Chemistry.',
                'required_subjects'  => ['ENG01', 'MATH01', 'PHY01', 'CHEM01'],
                'preferred_subjects' => ['BIO01'],
            ],
            [
                'name'               => 'Bachelor of Science in Statistics',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Natural and Applied Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits; strong credit in Mathematics/Additional Mathematics and 5 credits including English.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['PHY01', 'CHEM01', 'BIO01'],
                'grades'             => ['MATH01' => 3],
            ],
            [
                'name'               => 'Bachelor of Science in Actuarial Sciences (Honours)',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Natural and Applied Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits; min 4 points in English and min 2 points in Mathematics/Additional Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['PHY01', 'CHEM01'],
                'grades'             => ['ENG01' => 4, 'MATH01' => 2],
            ],
            [
                'name'               => 'Bachelor of Laws (LLB)',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Law, Economics and Government',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English. Strong credits in History, Social Studies and any two other subjects.',
                'required_subjects'  => ['ENG01'],
                'preferred_subjects' => ['HIST01', 'SOC01', 'MATH01', 'GEOG01', 'BK01'],
            ],
            [
                'name'               => 'Bachelor of Arts in Economics',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Law, Economics and Government',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BUS01', 'ACC01'],
            ],
            [
                'name'               => 'Bachelor of Arts in Development Economics',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Law, Economics and Government',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BUS01', 'HIST01'],
            ],
            [
                'name'               => 'Bachelor of Arts in Political Science',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Law, Economics and Government',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics and History or Social Studies.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['HIST01', 'SOC01', 'GEOG01', 'BK01'],
            ],
            [
                'name'               => 'Bachelor of Arts in Psychology',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Humanities and Social Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BIO01', 'SOC01', 'HIST01'],
            ],
            [
                'name'               => 'Bachelor of Arts in Social and Economic History',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Humanities and Social Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and History.',
                'required_subjects'  => ['ENG01', 'HIST01'],
                'preferred_subjects' => ['MATH01', 'GEOG01', 'SOC01'],
            ],
            [
                'name'               => 'Bachelor of Arts in Sociology',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Humanities and Social Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['SOC01', 'HIST01', 'GEOG01'],
            ],
            [
                'name'               => 'Bachelor of Arts in Linguistics and Communication',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Humanities and Social Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, and any two of: Chichewa, French, History, Social Studies.',
                'required_subjects'  => ['ENG01'],
                'preferred_subjects' => ['CHI01', 'FRE01', 'HIST01', 'SOC01'],
            ],
            [
                'name'               => 'Bachelor of Arts in Media and Communication Studies',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Humanities and Social Sciences',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and at least a pass in Mathematics.',
                'required_subjects'  => ['ENG01'],
                'preferred_subjects' => ['MATH01', 'HIST01', 'SOC01'],
            ],
            [
                'name'               => 'Bachelor of Education (Computer Science)',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Education',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Chemistry, Physics and any two of: Computer Studies, Biology, Geography, Agriculture.',
                'required_subjects'  => ['ENG01', 'MATH01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => ['COMP01', 'BIO01', 'GEOG01', 'AGRI01'],
            ],
            [
                'name'               => 'Bachelor of Education (Mathematics)',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Education',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Chemistry, Physics, Biology, plus min 4 points in Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'CHEM01', 'PHY01', 'BIO01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Education (Science)',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Education',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, Biology, Chemistry and Physics.',
                'required_subjects'  => ['ENG01', 'MATH01', 'BIO01', 'CHEM01', 'PHY01'],
                'preferred_subjects' => [],
            ],
            [
                'name'               => 'Bachelor of Education (English)',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Education',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including strong credit in English, Mathematics and any two humanities subjects.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['HIST01', 'SOC01', 'CHI01', 'FRE01'],
            ],
            [
                'name'               => 'Bachelor of Education (Social Sciences)',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Education',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English, Mathematics, History and Geography.',
                'required_subjects'  => ['ENG01', 'MATH01', 'HIST01', 'GEOG01'],
                'preferred_subjects' => ['SOC01', 'BK01'],
            ],
            [
                'name'               => 'Bachelor of Accountancy (Honours)',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Commerce and Management',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics; credit in Accounting or Business Studies is an added advantage.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['ACC01', 'BUS01'],
            ],
            [
                'name'               => 'Bachelor of Commerce in Business Administration',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Commerce and Management',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BUS01', 'ACC01'],
            ],
            [
                'name'               => 'Bachelor of Commerce in Banking and Finance',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Commerce and Management',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['ACC01', 'BUS01'],
            ],
            [
                'name'               => 'Bachelor of Commerce in Marketing',
                'university'         => 'University of Malawi (UNIMA)',
                'faculty'            => 'School of Commerce and Management',
                'minimum_points'     => 6,
                'entry_requirements' => 'Six MSCE credits including English and Mathematics.',
                'required_subjects'  => ['ENG01', 'MATH01'],
                'preferred_subjects' => ['BUS01', 'ACC01'],
            ],
        ];
    }
}
