<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Subject Combination Report — {{ $user->name }}</title>
<style>
body { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; line-height: 1.6; color: #000000; margin: 0; padding: 20px; }
.header { text-align: center; margin-bottom: 24px; border-bottom: 3px solid #2563eb; padding-bottom: 16px; }
.header h1 { color: #1e40af; margin: 0; font-size: 22px; font-weight: bold; }
.header h2 { color: #2563eb; margin: 6px 0 0; font-size: 16px; }
.header p { margin: 4px 0 0; color: #000000; font-size: 11px; }
.student-info { background: #eff6ff; padding: 12px 16px; border-radius: 6px; margin-bottom: 20px; }
.info-row { display: inline-block; width: 48%; margin-bottom: 4px; }
.label { font-weight: bold; color: #374151; display: inline-block; width: 110px; }
.value { color: #1e40af; }
.section-title { color: #1e40af; font-size: 14px; font-weight: bold; margin: 20px 0 10px; padding-bottom: 6px; border-bottom: 2px solid #2563eb; }
.combo-card { border: 1px solid #dbeafe; border-radius: 6px; padding: 14px; margin-bottom: 14px; page-break-inside: avoid; }
.combo-title { font-size: 14px; font-weight: bold; color: #1e40af; margin-bottom: 4px; }
.score-badge { background: #dbeafe; color: #1e40af; font-weight: bold; padding: 3px 10px; border-radius: 12px; font-size: 12px; float: right; }
.desc { font-size: 11px; color: #000000; margin-bottom: 10px; }
.subjects-grid { margin-top: 8px; }
.subject-pill { display: inline-block; background: #dbeafe; color: #1e40af; border: 1px solid #bfdbfe; padding: 3px 10px; border-radius: 12px; font-size: 11px; margin: 2px 3px 2px 0; }
.reason { font-style: italic; font-size: 10px; color: #000000; margin-top: 6px; }
.score-bar-bg { background: #dbeafe; height: 8px; border-radius: 4px; margin: 8px 0; }
.score-bar-fill { height: 8px; border-radius: 4px; background: #3b82f6; }
.tip-box { background: #eff6ff; border-left: 4px solid #3b82f6; padding: 10px 14px; border-radius: 4px; margin-top: 20px; font-size: 11px; }
.footer { text-align: center; font-size: 10px; color: #000000; margin-top: 30px; border-top: 1px solid #dbeafe; padding-top: 10px; }
</style>
</head>
<body>
<div class="header">
    <h1>Luwinga Secondary School</h1>
    <h2>Subject Combination Report</h2>
    <p>Smart Career &amp; Subject Guidance Tool &mdash; Generated {{ now()->format('F d, Y') }}</p>
</div>

<div class="student-info">
    <div class="info-row"><span class="label">Student:</span><span class="value">{{ $user->name }}</span></div>
    <div class="info-row"><span class="label">Email:</span><span class="value">{{ $user->email }}</span></div>
    <div class="info-row"><span class="label">Form Level:</span><span class="value">{{ $user->studentProfile?->form_level ?? 'N/A' }}</span></div>
    <div class="info-row"><span class="label">Stream:</span><span class="value">{{ $user->studentProfile?->stream ?? 'N/A' }}</span></div>
    <div class="info-row"><span class="label">Combinations:</span><span class="value">{{ $subjects->count() }} recommended</span></div>
    <div class="info-row"><span class="label">Report Date:</span><span class="value">{{ now()->format('d M Y') }}</span></div>
</div>

<div class="section-title">Recommended Subject Combinations</div>

@if($subjects->isEmpty())
<div style="text-align:center; padding:30px; color:#000000;">No subject combination recommendations found. Complete the career assessment to get your personalised subject recommendations.</div>
@else
@foreach($subjects as $rec)
@php
    $combo = $rec->recommended;
    $score = (int) $rec->confidence_score;
@endphp
@if($combo)
<div class="combo-card">
    <span class="score-badge">{{ $score }}% match</span>
    <div class="combo-title">{{ $combo->name }}</div>
    <div class="score-bar-bg">
        <div class="score-bar-fill" style="width: {{ $score }}%;"></div>
    </div>
    <div class="desc">{{ $combo->description }}</div>
    @if($combo->subjects->isNotEmpty())
    <div class="subjects-grid">
        <strong style="font-size:11px; color:#000000;">Subjects in this combination:</strong><br>
        @foreach($combo->subjects as $subject)
        <span class="subject-pill">{{ $subject->name }}</span>
        @endforeach
    </div>
    @endif
    @if($rec->reason)
    <div class="reason">{{ $rec->reason }}</div>
    @endif
</div>
@endif
@endforeach
@endif

<div class="tip-box">
    <strong>Guidance Note:</strong> Choose a subject combination that aligns with your top career interests. Discuss your choices with your class teacher or school counsellor before finalising.
</div>

<div class="footer">
    <p>This report is auto-generated by the Smart Career &amp; Subject Guidance Tool.</p>
    <p>Luwinga Secondary School, Mzuzu City, Malawi &mdash; For guidance, speak with your school counsellor.</p>
</div>
</body>
</html>
